export const RESET_STATE = 'RESET_STATE';
export const APPLY_SETTING = 'APPLY_SETTING';

export const SET_ROWS = 'SET_ROWS';
export const DELETE_ROW = 'DELETE_ROW';

export const SET_LOADING = 'SET_LOADING';
export const SET_LIVE_UPDATE = 'SET_LIVE_UPDATE';
export const SET_CURRENT_QUERY = 'SET_CURRENT_QUERY';

export const ADD_TO_EXISTING_FILTER = 'ADD_TO_EXISTING_FILTER';
export const DELETE_FILTER = 'DELETE_FILTER';
export const NEW_FILTER = 'NEW_FILTER';
export const SET_FILTER_ATTRIBUTE = 'SET_FILTER_ATTRIBUTE';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_LAST_PAGE = 'SET_LAST_PAGE';
export const SET_PAGINATION_PROPS = 'SET_PAGINATION_PROPS';
export const SET_PER_PAGE = 'SET_PER_PAGE';
export const SET_PER_PAGE_OPTIONS = 'SET_PER_PAGE_OPTIONS';

export const NEW_SORTING = 'NEW_SORTING';
export const DELETE_SORTING = 'DELETE_SORTING';
export const SET_SORTING_COLUMN = 'SET_SORTING_COLUMN';
export const SET_SORTING_DIRECTION = 'SET_SORTING_DIRECTION';
